### ISSUE TITLE
可以提供step-by-step说明文档吗？

### ISSUE THREAD

**Issue by happyyangyuan** [ZP-AlwaysWin/K8S-FastDFS#1]
如题

**Comment by ZP-AlwaysWin** [comment]
中文说明文档已经提供

**Comment by happyyangyuan** [comment]
还是谢谢你呀

**Comment by xavierzhao** [comment]
@happyyangyuan 请问helm中的哪个模版？

**Comment by happyyangyuan** [comment]
> @happyyangyuan 请问helm中的哪个模版？

自己瞎折腾的，在测试环境用了一段时间，后来架构把fastdfs换成minio了，然后minio比fastdfs不知道好用多少倍呀！
